version: '3'
services:
  redis:
    image: redis:4-alpine
    command: ['redis-server', '--protected-mode', 'no']
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=TwigC0DesRoot
      - MYSQL_DATABASE=kpi
      - MYSQL_PASSWORD=TwigC0Des
    volumes:
      - api_db:/var/lib/mysql
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - '5672:5672' # JMS 端口
  #     - '15672:15672' # 管理端口 default user:pass = guest:guest

volumes:
  api_db: {}
  redis-data: {}
