spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT}/${MYSQL_DATABASE}?useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
