server:
  port: ${SERVER_PORT:8080}
  error.whitelabel.enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT}/${MYSQL_DATABASE}?useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
  flyway:
    locations: "classpath:db/migration/mysql"
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

---

spring:
  profiles: dev
logging:
  level:
    ROOT: DEBUG
    org.apache.http: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: 'OFF'
    com.twigcodes: DEBUG

---

spring:
  profiles: prod
logging:
  level:
    ROOT: ERROR
    org.apache.http: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR
    com.twigcodes: ERROR